services:
  nginx:
    container_name: 'nginx'
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    networks:
      django_net:
        ipv4_address: 172.38.10.10
    tty: true
    ports:
      - 8080:80
      - 443:443
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./django/public/:/public/
    depends_on:
      - django

  django:
    container_name: 'django'
    build:
      context: ./docker/django
      dockerfile: Dockerfile
    networks:
      - django_net
      - db_net
      - eth_net
    tty: true
    volumes:
      - ./django/:/workspace
      - ./eth:/workspace/eth
    ports:
      - 3000:3000
      - 8000:8000
      - 8001:8001
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME
      - OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID
      - OAUTH_SECRET_ID=$OAUTH_SECRET_ID
      - TWILIO_SERVICE_SID=$TWILIO_SERVICE_SID
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - BREVO_API_KEY=$BREVO_API_KEY
      - BREVO_SENDER_ADDRESS=$BREVO_SENDER_ADDRESS

  eth:
    container_name: 'eth'
    build:
      context: .
      dockerfile: ./docker/eth/Dockerfile
    networks:
      - eth_net
    tty: true
    volumes:
      - ./eth:/workspace/eth
    expose:
      - '8545'

networks:
  django_net:
    name: django_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.10.0/24
  db_net:
    name: db_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.20.0/24
  eth_net:
    name: eth_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.30.0/24
