networks:
  django_net:
    name: django_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.10.0/24
  db_net:
    name: db_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.20.0/24
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    networks:
      django_net:
        ipv4_address: 172.38.10.10
    tty: true
    ports:
      - 8080:80
      - 443:443
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./ft_trans/public/:/public/
    depends_on:
      - django
  db:
    container_name: "db"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    networks:
      - db_net
    tty: true
    volumes:
      - ./db_volume/:/var/lib/postgresql/data
    depends_on:
      - django
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME


  django:
    container_name: "django"
    build:
      context: ./docker/django
      dockerfile: Dockerfile
    networks:
      - django_net
      - db_net
    tty: true
    volumes:
      - ./ft_trans/:/workspace
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME
    command:
      /bin/sh -c '
        cp /tmp/server.key /workspace/ &&
        cp /tmp/server.crt /workspace/ &&
        cp  /tmp/make_db_setting.sh /workspace/make_db_setting.sh &&
        sh /workspace/make_db_setting.sh &&
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        daphne -e  ssl:8000:privateKey=/workspace/server.key:certKey=/workspace/server.crt ft_trans.asgi:application
      '
