networks:
  django_net:
    name: django_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.10.0/24
  db_net:
    name: db_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.20.0/24
services:
  nginx:
    container_name: 'nginx'
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    networks:
      django_net:
        ipv4_address: 172.38.10.10
    tty: true
    ports:
      - 8080:80
      - 443:443
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./django//public/:/public/
  db:
    container_name: 'db'
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    networks:
      - db_net
    tty: true
    volumes:
      - ./db_volume/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 8s
      timeout: 3s
      retries: 5
      start_period: 5s

  django:
    container_name: 'django'
    build:
      context: ./docker/django
      dockerfile: Dockerfile
    networks:
      - django_net
      - db_net
    tty: true
    volumes:
      - ./django/:/workspace
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
      - 8000:8000
      - 8001:8001
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_DJANGO_USER=$POSTGRES_DJANGO_USER
      - POSTGRES_DJANGO_PASSWORD=$POSTGRES_DJANGO_PASSWORD
      - POSTGRES_DJANGO_DB_NAME=$POSTGRES_DJANGO_DB_NAME
      - OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID
      - OAUTH_SECRET_ID=$OAUTH_SECRET_ID
      - TWILIO_SERVICE_SID=$TWILIO_SERVICE_SID
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - BREVO_API_KEY=$BREVO_API_KEY
      - BREVO_SENDER_ADDRESS=$BREVO_SENDER_ADDRESS
    command: /bin/sh -c '
      cp /tmp/make_db_setting.sh ./backend/make_db_setting.sh &&
      sh ./backend/make_db_setting.sh &&
      cd backend &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      (cd ../frontend && npm install && npm run build) &&
      daphne -e  ssl:8000:privateKey=/tmp/server.key:certKey=/tmp/server.crt ft_trans.asgi:application
      '
