# Generated by Django 5.0.4 on 2024-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='ユーザー名')),
                ('email', models.CharField(max_length=256, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='姓')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='名')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuer')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('created_at', models.DateTimeField(null=True, verbose_name='ft_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ft_updateded_at')),
                ('groups', models.ManyToManyField(related_name='ft_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='ft_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
